server:
  port: 8080

spring:
  application:
    name: users
  datasource:
    username: ${DB_USERNAME:pedyk}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    generate-ddl: false


  sql:
    init:
      platform: postgresql
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql