apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  namespace: kubernetes-microservices-task2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: norbertpedyk/post-image:version11
          envFrom:
            - configMapRef:
                name: post-config
            - secretRef:
                name: secret
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

---

apiVersion: v1
kind: Service
metadata:
  name: post
  namespace: kubernetes-microservices-task2
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - name: post
      port: 8081
      targetPort: 8081
      nodePort: 31516
      protocol: TCP




#readinessProbe:
#  httpGet:
#    path: /healthz
#    port: 8080
#  initialDelaySeconds: 5
#  periodSeconds: 3
#  livenessProbe:
#    httpGet:
#      path: /healthz
#      port: 8080
#    initialDelaySeconds: 30
#    periodSeconds: 10


#  - name: postgres-healthcheck-container
#      image: postgres:latest
#      command: ["sh", "-c", "pg_isready -h <first-pod-name> -p 5432"]
#      readinessProbe:
#        exec:
#          command: ["pg_isready"]
#        initialDelaySeconds: 5
#        periodSeconds: 3
#      livenessProbe:
#        exec:
#          command: ["pg_isready"]
#        initialDelaySeconds: 30
#        periodSeconds: 10

#readinessProbe:
#  exec:
#    command:
#      - sh
#      - -c
#      - "nc -z post-db 5433 && echo 'DB connection succeeded'"
#  initialDelaySeconds: 5
#  periodSeconds: 5
