server:
  port: 8081

spring:
  application:
    name: post
  datasource:
    username: ${DB_USERNAME:pedyk}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/posts}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    generate-ddl: false

  sql:
    init:
      platform: postgresql
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

custom:
  user-service-url: ${USER_SERVICE_URL:http://localhost:8080/users/}