apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mychart.labels.current_date" . | nindent 4 }}
    {{- include "mychart.labels.version" . | nindent 4 }}
data:
  USER_SERVICE_URL: "http://user:8080/users/"
  DB_URL: "jdbc:postgresql://post-db:5433/posts"
  init.sql:
    CREATE TABLE if NOT EXISTS posts
    (
    id
    BIGSERIAL
    PRIMARY
    KEY,
    author_id
    BIGINT
    NOT
    NULL,
    text
    TEXT
    NOT
    NULL,
    topic
    TEXT
    NOT
    NULL,
    posted_at
    TIMESTAMP
    NOT
    NULL
    );
    CREATE SEQUENCE if not EXISTS post_seq START 7;
    TRUNCATE TABLE posts;
    INSERT INTO posts (id, author_id, text,topic, posted_at)
    VALUES (1, 1, 'This is my first post','topic 1' ,'2022-01-01 12:00:00'),
    (2, 1, 'Hello World', 'topic 2','2022-02-01 12:00:00'),
    (3, 1, 'I love PostgreSQL','topic 3' ,'2022-03-01 12:00:00'),
    (4, 2, 'Today is a beautiful day','topic 4' ,'2022-04-01 12:00:00'),
    (5, 3, 'My thoughts on programming','topic 5' ,'2022-05-01 12:00:00'),
    (6, 3, 'Why I switched to PostgreSQL', 'topic 6','2022-06-01 12:00:00');

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mychart.labels.current_date" . | nindent 4 }}
    {{- include "mychart.labels.version" . | nindent 4 }}
data:
  DB_URL: "jdbc:postgresql://user-db:5432/users"
  init.sql:
    CREATE TABLE IF NOT EXISTS users
    (
    id        BIGSERIAL PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    amount    VARCHAR(255) NOT NULL
    );
    TRUNCATE TABLE users;
    INSERT INTO users (id, user_name, amount)
    VALUES (1, 'John Doe', '3'),
    (2, 'Jane Smith', '1'),
    (3, 'Bob Johnson', '2');

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mychart.labels.current_date" . | nindent 4 }}
    {{- include "mychart.labels.version" . | nindent 4 }}
data:
  POSTGRES_USER: pedyk
  POSTGRES_DB: users


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-post-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mychart.labels.current_date" . | nindent 4 }}
    {{- include "mychart.labels.version" . | nindent 4 }}
data:
  POSTGRES_USER: pedyk
  POSTGRES_DB: posts


