apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.postReplicas }}
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: norbertpedyk/post-image:version11
          envFrom:
            - configMapRef:
                name: post-config
            - secretRef:
                name: secret
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

---

apiVersion: v1
kind: Service
metadata:
  name: post
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - name: post
      port: 8081
      targetPort: 8081
      nodePort: 31516
      protocol: TCP


