apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
  DB_USERNAME: cGVkeWt=     # base64 encoded "pedyk"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
