apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.userReplicas }}
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: norbertpedyk/user-image:version4
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: secret
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0


---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - name: user
      port: 8080
      targetPort: 8080
      nodePort: 31515
      protocol: TCP